// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SessionDestroyResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionDestroyResponse) Reset()         { *m = SessionDestroyResponse{} }
func (m *SessionDestroyResponse) String() string { return proto.CompactTextString(m) }
func (*SessionDestroyResponse) ProtoMessage()    {}
func (*SessionDestroyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *SessionDestroyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionDestroyResponse.Unmarshal(m, b)
}
func (m *SessionDestroyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionDestroyResponse.Marshal(b, m, deterministic)
}
func (m *SessionDestroyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionDestroyResponse.Merge(m, src)
}
func (m *SessionDestroyResponse) XXX_Size() int {
	return xxx_messageInfo_SessionDestroyResponse.Size(m)
}
func (m *SessionDestroyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionDestroyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SessionDestroyResponse proto.InternalMessageInfo

func (m *SessionDestroyResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type SessionAuthResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionAuthResponse) Reset()         { *m = SessionAuthResponse{} }
func (m *SessionAuthResponse) String() string { return proto.CompactTextString(m) }
func (*SessionAuthResponse) ProtoMessage()    {}
func (*SessionAuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *SessionAuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionAuthResponse.Unmarshal(m, b)
}
func (m *SessionAuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionAuthResponse.Marshal(b, m, deterministic)
}
func (m *SessionAuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionAuthResponse.Merge(m, src)
}
func (m *SessionAuthResponse) XXX_Size() int {
	return xxx_messageInfo_SessionAuthResponse.Size(m)
}
func (m *SessionAuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionAuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SessionAuthResponse proto.InternalMessageInfo

func (m *SessionAuthResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type SessionGeneralRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionGeneralRequest) Reset()         { *m = SessionGeneralRequest{} }
func (m *SessionGeneralRequest) String() string { return proto.CompactTextString(m) }
func (*SessionGeneralRequest) ProtoMessage()    {}
func (*SessionGeneralRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *SessionGeneralRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionGeneralRequest.Unmarshal(m, b)
}
func (m *SessionGeneralRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionGeneralRequest.Marshal(b, m, deterministic)
}
func (m *SessionGeneralRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionGeneralRequest.Merge(m, src)
}
func (m *SessionGeneralRequest) XXX_Size() int {
	return xxx_messageInfo_SessionGeneralRequest.Size(m)
}
func (m *SessionGeneralRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionGeneralRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionGeneralRequest proto.InternalMessageInfo

func (m *SessionGeneralRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type SessionGeneralResponse struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionGeneralResponse) Reset()         { *m = SessionGeneralResponse{} }
func (m *SessionGeneralResponse) String() string { return proto.CompactTextString(m) }
func (*SessionGeneralResponse) ProtoMessage()    {}
func (*SessionGeneralResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *SessionGeneralResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionGeneralResponse.Unmarshal(m, b)
}
func (m *SessionGeneralResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionGeneralResponse.Marshal(b, m, deterministic)
}
func (m *SessionGeneralResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionGeneralResponse.Merge(m, src)
}
func (m *SessionGeneralResponse) XXX_Size() int {
	return xxx_messageInfo_SessionGeneralResponse.Size(m)
}
func (m *SessionGeneralResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionGeneralResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SessionGeneralResponse proto.InternalMessageInfo

func (m *SessionGeneralResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func init() {
	proto.RegisterType((*SessionDestroyResponse)(nil), "pb.SessionDestroyResponse")
	proto.RegisterType((*SessionAuthResponse)(nil), "pb.SessionAuthResponse")
	proto.RegisterType((*SessionGeneralRequest)(nil), "pb.SessionGeneralRequest")
	proto.RegisterType((*SessionGeneralResponse)(nil), "pb.SessionGeneralResponse")
}

func init() {
	proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874)
}

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xd2, 0xe0, 0x12, 0x0b, 0x4e,
	0x2d, 0x2e, 0xce, 0xcc, 0xcf, 0x73, 0x49, 0x2d, 0x2e, 0x29, 0xca, 0xaf, 0x0c, 0x4a, 0x2d, 0x2e,
	0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0xe2, 0xe3, 0x62, 0xca, 0xcf, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x08, 0x62, 0xca, 0xcf, 0x56, 0x52, 0xe5, 0x12, 0x86, 0xaa, 0x74, 0x2c, 0x2d, 0xc9, 0xc0, 0xa9,
	0xcc, 0x8c, 0x4b, 0x14, 0xaa, 0xcc, 0x3d, 0x35, 0x2f, 0xb5, 0x28, 0x31, 0x27, 0x28, 0xb5, 0xb0,
	0x34, 0xb5, 0xb8, 0x44, 0x48, 0x96, 0x8b, 0xab, 0x18, 0x22, 0x11, 0x9f, 0x99, 0x02, 0xd6, 0xc0,
	0x19, 0xc4, 0x09, 0x15, 0xf1, 0x4c, 0x51, 0x32, 0x87, 0x3b, 0x04, 0xae, 0x0f, 0x6a, 0x03, 0x7e,
	0x8d, 0x46, 0xf7, 0x19, 0xb9, 0x58, 0x40, 0x2e, 0x12, 0x72, 0xe6, 0xe2, 0x46, 0x72, 0xa0, 0x90,
	0xa4, 0x5e, 0x41, 0x92, 0x1e, 0x56, 0xa7, 0x48, 0x89, 0x23, 0x49, 0x21, 0x7b, 0x46, 0x89, 0x41,
	0xc8, 0x9d, 0x8b, 0x07, 0x2a, 0x11, 0x5c, 0x92, 0x58, 0x54, 0x82, 0xcf, 0x14, 0x29, 0x6c, 0x52,
	0x70, 0x83, 0x3c, 0xb9, 0xf8, 0x50, 0x03, 0x96, 0x58, 0xa3, 0xd0, 0xe2, 0x41, 0x89, 0x21, 0x89,
	0x0d, 0x1c, 0x5d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x83, 0x30, 0x6c, 0xce, 0xbc, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	SessionAuth(ctx context.Context, in *SessionGeneralRequest, opts ...grpc.CallOption) (*SessionAuthResponse, error)
	SessionStart(ctx context.Context, in *SessionGeneralRequest, opts ...grpc.CallOption) (*SessionGeneralResponse, error)
	SessionDestroy(ctx context.Context, in *SessionGeneralRequest, opts ...grpc.CallOption) (*SessionDestroyResponse, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) SessionAuth(ctx context.Context, in *SessionGeneralRequest, opts ...grpc.CallOption) (*SessionAuthResponse, error) {
	out := new(SessionAuthResponse)
	err := c.cc.Invoke(ctx, "/pb.Auth/SessionAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) SessionStart(ctx context.Context, in *SessionGeneralRequest, opts ...grpc.CallOption) (*SessionGeneralResponse, error) {
	out := new(SessionGeneralResponse)
	err := c.cc.Invoke(ctx, "/pb.Auth/SessionStart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) SessionDestroy(ctx context.Context, in *SessionGeneralRequest, opts ...grpc.CallOption) (*SessionDestroyResponse, error) {
	out := new(SessionDestroyResponse)
	err := c.cc.Invoke(ctx, "/pb.Auth/SessionDestroy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	SessionAuth(context.Context, *SessionGeneralRequest) (*SessionAuthResponse, error)
	SessionStart(context.Context, *SessionGeneralRequest) (*SessionGeneralResponse, error)
	SessionDestroy(context.Context, *SessionGeneralRequest) (*SessionDestroyResponse, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) SessionAuth(ctx context.Context, req *SessionGeneralRequest) (*SessionAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SessionAuth not implemented")
}
func (*UnimplementedAuthServer) SessionStart(ctx context.Context, req *SessionGeneralRequest) (*SessionGeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SessionStart not implemented")
}
func (*UnimplementedAuthServer) SessionDestroy(ctx context.Context, req *SessionGeneralRequest) (*SessionDestroyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SessionDestroy not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_SessionAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionGeneralRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).SessionAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Auth/SessionAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).SessionAuth(ctx, req.(*SessionGeneralRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_SessionStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionGeneralRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).SessionStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Auth/SessionStart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).SessionStart(ctx, req.(*SessionGeneralRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_SessionDestroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionGeneralRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).SessionDestroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Auth/SessionDestroy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).SessionDestroy(ctx, req.(*SessionGeneralRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SessionAuth",
			Handler:    _Auth_SessionAuth_Handler,
		},
		{
			MethodName: "SessionStart",
			Handler:    _Auth_SessionStart_Handler,
		},
		{
			MethodName: "SessionDestroy",
			Handler:    _Auth_SessionDestroy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
