// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type StopFollowingRequest struct {
	SourceUserId         uint64   `protobuf:"varint,1,opt,name=source_user_id,json=sourceUserId,proto3" json:"source_user_id,omitempty"`
	TargetUserId         uint64   `protobuf:"varint,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopFollowingRequest) Reset()         { *m = StopFollowingRequest{} }
func (m *StopFollowingRequest) String() string { return proto.CompactTextString(m) }
func (*StopFollowingRequest) ProtoMessage()    {}
func (*StopFollowingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{2}
}

func (m *StopFollowingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopFollowingRequest.Unmarshal(m, b)
}
func (m *StopFollowingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopFollowingRequest.Marshal(b, m, deterministic)
}
func (m *StopFollowingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopFollowingRequest.Merge(m, src)
}
func (m *StopFollowingRequest) XXX_Size() int {
	return xxx_messageInfo_StopFollowingRequest.Size(m)
}
func (m *StopFollowingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopFollowingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopFollowingRequest proto.InternalMessageInfo

func (m *StopFollowingRequest) GetSourceUserId() uint64 {
	if m != nil {
		return m.SourceUserId
	}
	return 0
}

func (m *StopFollowingRequest) GetTargetUserId() uint64 {
	if m != nil {
		return m.TargetUserId
	}
	return 0
}

type StopFollowingResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopFollowingResponse) Reset()         { *m = StopFollowingResponse{} }
func (m *StopFollowingResponse) String() string { return proto.CompactTextString(m) }
func (*StopFollowingResponse) ProtoMessage()    {}
func (*StopFollowingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{3}
}

func (m *StopFollowingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopFollowingResponse.Unmarshal(m, b)
}
func (m *StopFollowingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopFollowingResponse.Marshal(b, m, deterministic)
}
func (m *StopFollowingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopFollowingResponse.Merge(m, src)
}
func (m *StopFollowingResponse) XXX_Size() int {
	return xxx_messageInfo_StopFollowingResponse.Size(m)
}
func (m *StopFollowingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopFollowingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopFollowingResponse proto.InternalMessageInfo

func (m *StopFollowingResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type StartFollowingRequest struct {
	SourceUserId         uint64   `protobuf:"varint,1,opt,name=source_user_id,json=sourceUserId,proto3" json:"source_user_id,omitempty"`
	TargetUserId         uint64   `protobuf:"varint,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartFollowingRequest) Reset()         { *m = StartFollowingRequest{} }
func (m *StartFollowingRequest) String() string { return proto.CompactTextString(m) }
func (*StartFollowingRequest) ProtoMessage()    {}
func (*StartFollowingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{4}
}

func (m *StartFollowingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartFollowingRequest.Unmarshal(m, b)
}
func (m *StartFollowingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartFollowingRequest.Marshal(b, m, deterministic)
}
func (m *StartFollowingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartFollowingRequest.Merge(m, src)
}
func (m *StartFollowingRequest) XXX_Size() int {
	return xxx_messageInfo_StartFollowingRequest.Size(m)
}
func (m *StartFollowingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartFollowingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartFollowingRequest proto.InternalMessageInfo

func (m *StartFollowingRequest) GetSourceUserId() uint64 {
	if m != nil {
		return m.SourceUserId
	}
	return 0
}

func (m *StartFollowingRequest) GetTargetUserId() uint64 {
	if m != nil {
		return m.TargetUserId
	}
	return 0
}

type StartFollowingResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartFollowingResponse) Reset()         { *m = StartFollowingResponse{} }
func (m *StartFollowingResponse) String() string { return proto.CompactTextString(m) }
func (*StartFollowingResponse) ProtoMessage()    {}
func (*StartFollowingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{5}
}

func (m *StartFollowingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartFollowingResponse.Unmarshal(m, b)
}
func (m *StartFollowingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartFollowingResponse.Marshal(b, m, deterministic)
}
func (m *StartFollowingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartFollowingResponse.Merge(m, src)
}
func (m *StartFollowingResponse) XXX_Size() int {
	return xxx_messageInfo_StartFollowingResponse.Size(m)
}
func (m *StartFollowingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartFollowingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartFollowingResponse proto.InternalMessageInfo

func (m *StartFollowingResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type UserCheckWhetherFollowingRequest struct {
	SourceUserId         uint64   `protobuf:"varint,1,opt,name=source_user_id,json=sourceUserId,proto3" json:"source_user_id,omitempty"`
	TargetUserId         uint64   `protobuf:"varint,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCheckWhetherFollowingRequest) Reset()         { *m = UserCheckWhetherFollowingRequest{} }
func (m *UserCheckWhetherFollowingRequest) String() string { return proto.CompactTextString(m) }
func (*UserCheckWhetherFollowingRequest) ProtoMessage()    {}
func (*UserCheckWhetherFollowingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{6}
}

func (m *UserCheckWhetherFollowingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCheckWhetherFollowingRequest.Unmarshal(m, b)
}
func (m *UserCheckWhetherFollowingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCheckWhetherFollowingRequest.Marshal(b, m, deterministic)
}
func (m *UserCheckWhetherFollowingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCheckWhetherFollowingRequest.Merge(m, src)
}
func (m *UserCheckWhetherFollowingRequest) XXX_Size() int {
	return xxx_messageInfo_UserCheckWhetherFollowingRequest.Size(m)
}
func (m *UserCheckWhetherFollowingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCheckWhetherFollowingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserCheckWhetherFollowingRequest proto.InternalMessageInfo

func (m *UserCheckWhetherFollowingRequest) GetSourceUserId() uint64 {
	if m != nil {
		return m.SourceUserId
	}
	return 0
}

func (m *UserCheckWhetherFollowingRequest) GetTargetUserId() uint64 {
	if m != nil {
		return m.TargetUserId
	}
	return 0
}

type UserCheckWhetherFollowingResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCheckWhetherFollowingResponse) Reset()         { *m = UserCheckWhetherFollowingResponse{} }
func (m *UserCheckWhetherFollowingResponse) String() string { return proto.CompactTextString(m) }
func (*UserCheckWhetherFollowingResponse) ProtoMessage()    {}
func (*UserCheckWhetherFollowingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{7}
}

func (m *UserCheckWhetherFollowingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCheckWhetherFollowingResponse.Unmarshal(m, b)
}
func (m *UserCheckWhetherFollowingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCheckWhetherFollowingResponse.Marshal(b, m, deterministic)
}
func (m *UserCheckWhetherFollowingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCheckWhetherFollowingResponse.Merge(m, src)
}
func (m *UserCheckWhetherFollowingResponse) XXX_Size() int {
	return xxx_messageInfo_UserCheckWhetherFollowingResponse.Size(m)
}
func (m *UserCheckWhetherFollowingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCheckWhetherFollowingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserCheckWhetherFollowingResponse proto.InternalMessageInfo

func (m *UserCheckWhetherFollowingResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type FindAllUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAllUsersRequest) Reset()         { *m = FindAllUsersRequest{} }
func (m *FindAllUsersRequest) String() string { return proto.CompactTextString(m) }
func (*FindAllUsersRequest) ProtoMessage()    {}
func (*FindAllUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{8}
}

func (m *FindAllUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllUsersRequest.Unmarshal(m, b)
}
func (m *FindAllUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllUsersRequest.Marshal(b, m, deterministic)
}
func (m *FindAllUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllUsersRequest.Merge(m, src)
}
func (m *FindAllUsersRequest) XXX_Size() int {
	return xxx_messageInfo_FindAllUsersRequest.Size(m)
}
func (m *FindAllUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllUsersRequest proto.InternalMessageInfo

type FindAllUsersResponse struct {
	Users                []*UserEntity `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FindAllUsersResponse) Reset()         { *m = FindAllUsersResponse{} }
func (m *FindAllUsersResponse) String() string { return proto.CompactTextString(m) }
func (*FindAllUsersResponse) ProtoMessage()    {}
func (*FindAllUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{9}
}

func (m *FindAllUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllUsersResponse.Unmarshal(m, b)
}
func (m *FindAllUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllUsersResponse.Marshal(b, m, deterministic)
}
func (m *FindAllUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllUsersResponse.Merge(m, src)
}
func (m *FindAllUsersResponse) XXX_Size() int {
	return xxx_messageInfo_FindAllUsersResponse.Size(m)
}
func (m *FindAllUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllUsersResponse proto.InternalMessageInfo

func (m *FindAllUsersResponse) GetUsers() []*UserEntity {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserAddTweetRequest struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAddTweetRequest) Reset()         { *m = UserAddTweetRequest{} }
func (m *UserAddTweetRequest) String() string { return proto.CompactTextString(m) }
func (*UserAddTweetRequest) ProtoMessage()    {}
func (*UserAddTweetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{10}
}

func (m *UserAddTweetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAddTweetRequest.Unmarshal(m, b)
}
func (m *UserAddTweetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAddTweetRequest.Marshal(b, m, deterministic)
}
func (m *UserAddTweetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAddTweetRequest.Merge(m, src)
}
func (m *UserAddTweetRequest) XXX_Size() int {
	return xxx_messageInfo_UserAddTweetRequest.Size(m)
}
func (m *UserAddTweetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAddTweetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserAddTweetRequest proto.InternalMessageInfo

func (m *UserAddTweetRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserAddTweetRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type UserAddTweetResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAddTweetResponse) Reset()         { *m = UserAddTweetResponse{} }
func (m *UserAddTweetResponse) String() string { return proto.CompactTextString(m) }
func (*UserAddTweetResponse) ProtoMessage()    {}
func (*UserAddTweetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{11}
}

func (m *UserAddTweetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAddTweetResponse.Unmarshal(m, b)
}
func (m *UserAddTweetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAddTweetResponse.Marshal(b, m, deterministic)
}
func (m *UserAddTweetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAddTweetResponse.Merge(m, src)
}
func (m *UserAddTweetResponse) XXX_Size() int {
	return xxx_messageInfo_UserAddTweetResponse.Size(m)
}
func (m *UserAddTweetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAddTweetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserAddTweetResponse proto.InternalMessageInfo

func (m *UserAddTweetResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type UserSelectByIdResponse struct {
	User                 *UserEntity `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserSelectByIdResponse) Reset()         { *m = UserSelectByIdResponse{} }
func (m *UserSelectByIdResponse) String() string { return proto.CompactTextString(m) }
func (*UserSelectByIdResponse) ProtoMessage()    {}
func (*UserSelectByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{12}
}

func (m *UserSelectByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSelectByIdResponse.Unmarshal(m, b)
}
func (m *UserSelectByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSelectByIdResponse.Marshal(b, m, deterministic)
}
func (m *UserSelectByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSelectByIdResponse.Merge(m, src)
}
func (m *UserSelectByIdResponse) XXX_Size() int {
	return xxx_messageInfo_UserSelectByIdResponse.Size(m)
}
func (m *UserSelectByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSelectByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserSelectByIdResponse proto.InternalMessageInfo

func (m *UserSelectByIdResponse) GetUser() *UserEntity {
	if m != nil {
		return m.User
	}
	return nil
}

type UserEntity struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Followers            []uint64 `protobuf:"varint,4,rep,packed,name=followers,proto3" json:"followers,omitempty"`
	Followings           []uint64 `protobuf:"varint,5,rep,packed,name=followings,proto3" json:"followings,omitempty"`
	Tweets               []uint64 `protobuf:"varint,6,rep,packed,name=tweets,proto3" json:"tweets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserEntity) Reset()         { *m = UserEntity{} }
func (m *UserEntity) String() string { return proto.CompactTextString(m) }
func (*UserEntity) ProtoMessage()    {}
func (*UserEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{13}
}

func (m *UserEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEntity.Unmarshal(m, b)
}
func (m *UserEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEntity.Marshal(b, m, deterministic)
}
func (m *UserEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEntity.Merge(m, src)
}
func (m *UserEntity) XXX_Size() int {
	return xxx_messageInfo_UserEntity.Size(m)
}
func (m *UserEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEntity.DiscardUnknown(m)
}

var xxx_messageInfo_UserEntity proto.InternalMessageInfo

func (m *UserEntity) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserEntity) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserEntity) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserEntity) GetFollowers() []uint64 {
	if m != nil {
		return m.Followers
	}
	return nil
}

func (m *UserEntity) GetFollowings() []uint64 {
	if m != nil {
		return m.Followings
	}
	return nil
}

func (m *UserEntity) GetTweets() []uint64 {
	if m != nil {
		return m.Tweets
	}
	return nil
}

type UserSelectByNameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSelectByNameRequest) Reset()         { *m = UserSelectByNameRequest{} }
func (m *UserSelectByNameRequest) String() string { return proto.CompactTextString(m) }
func (*UserSelectByNameRequest) ProtoMessage()    {}
func (*UserSelectByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{14}
}

func (m *UserSelectByNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSelectByNameRequest.Unmarshal(m, b)
}
func (m *UserSelectByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSelectByNameRequest.Marshal(b, m, deterministic)
}
func (m *UserSelectByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSelectByNameRequest.Merge(m, src)
}
func (m *UserSelectByNameRequest) XXX_Size() int {
	return xxx_messageInfo_UserSelectByNameRequest.Size(m)
}
func (m *UserSelectByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSelectByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserSelectByNameRequest proto.InternalMessageInfo

func (m *UserSelectByNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserSelectByNameResponse struct {
	User                 *UserEntity `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserSelectByNameResponse) Reset()         { *m = UserSelectByNameResponse{} }
func (m *UserSelectByNameResponse) String() string { return proto.CompactTextString(m) }
func (*UserSelectByNameResponse) ProtoMessage()    {}
func (*UserSelectByNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{15}
}

func (m *UserSelectByNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSelectByNameResponse.Unmarshal(m, b)
}
func (m *UserSelectByNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSelectByNameResponse.Marshal(b, m, deterministic)
}
func (m *UserSelectByNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSelectByNameResponse.Merge(m, src)
}
func (m *UserSelectByNameResponse) XXX_Size() int {
	return xxx_messageInfo_UserSelectByNameResponse.Size(m)
}
func (m *UserSelectByNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSelectByNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserSelectByNameResponse proto.InternalMessageInfo

func (m *UserSelectByNameResponse) GetUser() *UserEntity {
	if m != nil {
		return m.User
	}
	return nil
}

type NewUserRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserPwd              string   `protobuf:"bytes,2,opt,name=user_pwd,json=userPwd,proto3" json:"user_pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserRequest) Reset()         { *m = NewUserRequest{} }
func (m *NewUserRequest) String() string { return proto.CompactTextString(m) }
func (*NewUserRequest) ProtoMessage()    {}
func (*NewUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{16}
}

func (m *NewUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserRequest.Unmarshal(m, b)
}
func (m *NewUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserRequest.Marshal(b, m, deterministic)
}
func (m *NewUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserRequest.Merge(m, src)
}
func (m *NewUserRequest) XXX_Size() int {
	return xxx_messageInfo_NewUserRequest.Size(m)
}
func (m *NewUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserRequest proto.InternalMessageInfo

func (m *NewUserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *NewUserRequest) GetUserPwd() string {
	if m != nil {
		return m.UserPwd
	}
	return ""
}

type NewUserResponse struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserResponse) Reset()         { *m = NewUserResponse{} }
func (m *NewUserResponse) String() string { return proto.CompactTextString(m) }
func (*NewUserResponse) ProtoMessage()    {}
func (*NewUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{17}
}

func (m *NewUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserResponse.Unmarshal(m, b)
}
func (m *NewUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserResponse.Marshal(b, m, deterministic)
}
func (m *NewUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserResponse.Merge(m, src)
}
func (m *NewUserResponse) XXX_Size() int {
	return xxx_messageInfo_NewUserResponse.Size(m)
}
func (m *NewUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserResponse proto.InternalMessageInfo

func (m *NewUserResponse) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type NewTweetRequest struct {
	UserId               uint64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTweetRequest) Reset()         { *m = NewTweetRequest{} }
func (m *NewTweetRequest) String() string { return proto.CompactTextString(m) }
func (*NewTweetRequest) ProtoMessage()    {}
func (*NewTweetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{18}
}

func (m *NewTweetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTweetRequest.Unmarshal(m, b)
}
func (m *NewTweetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTweetRequest.Marshal(b, m, deterministic)
}
func (m *NewTweetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTweetRequest.Merge(m, src)
}
func (m *NewTweetRequest) XXX_Size() int {
	return xxx_messageInfo_NewTweetRequest.Size(m)
}
func (m *NewTweetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTweetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewTweetRequest proto.InternalMessageInfo

func (m *NewTweetRequest) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *NewTweetRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type NewTweetResponse struct {
	TweetId              uint64   `protobuf:"varint,1,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTweetResponse) Reset()         { *m = NewTweetResponse{} }
func (m *NewTweetResponse) String() string { return proto.CompactTextString(m) }
func (*NewTweetResponse) ProtoMessage()    {}
func (*NewTweetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{19}
}

func (m *NewTweetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTweetResponse.Unmarshal(m, b)
}
func (m *NewTweetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTweetResponse.Marshal(b, m, deterministic)
}
func (m *NewTweetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTweetResponse.Merge(m, src)
}
func (m *NewTweetResponse) XXX_Size() int {
	return xxx_messageInfo_NewTweetResponse.Size(m)
}
func (m *NewTweetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTweetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewTweetResponse proto.InternalMessageInfo

func (m *NewTweetResponse) GetTweetId() uint64 {
	if m != nil {
		return m.TweetId
	}
	return 0
}

type SelectByIdRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelectByIdRequest) Reset()         { *m = SelectByIdRequest{} }
func (m *SelectByIdRequest) String() string { return proto.CompactTextString(m) }
func (*SelectByIdRequest) ProtoMessage()    {}
func (*SelectByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{20}
}

func (m *SelectByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectByIdRequest.Unmarshal(m, b)
}
func (m *SelectByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectByIdRequest.Marshal(b, m, deterministic)
}
func (m *SelectByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectByIdRequest.Merge(m, src)
}
func (m *SelectByIdRequest) XXX_Size() int {
	return xxx_messageInfo_SelectByIdRequest.Size(m)
}
func (m *SelectByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SelectByIdRequest proto.InternalMessageInfo

func (m *SelectByIdRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type TweetSelectByIdResponse struct {
	Msg                  *TweetEntity `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TweetSelectByIdResponse) Reset()         { *m = TweetSelectByIdResponse{} }
func (m *TweetSelectByIdResponse) String() string { return proto.CompactTextString(m) }
func (*TweetSelectByIdResponse) ProtoMessage()    {}
func (*TweetSelectByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{21}
}

func (m *TweetSelectByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TweetSelectByIdResponse.Unmarshal(m, b)
}
func (m *TweetSelectByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TweetSelectByIdResponse.Marshal(b, m, deterministic)
}
func (m *TweetSelectByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TweetSelectByIdResponse.Merge(m, src)
}
func (m *TweetSelectByIdResponse) XXX_Size() int {
	return xxx_messageInfo_TweetSelectByIdResponse.Size(m)
}
func (m *TweetSelectByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TweetSelectByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TweetSelectByIdResponse proto.InternalMessageInfo

func (m *TweetSelectByIdResponse) GetMsg() *TweetEntity {
	if m != nil {
		return m.Msg
	}
	return nil
}

type TweetEntity struct {
	TweetId              uint64   `protobuf:"varint,1,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id,omitempty"`
	UserId               uint64   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedTime          string   `protobuf:"bytes,4,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TweetEntity) Reset()         { *m = TweetEntity{} }
func (m *TweetEntity) String() string { return proto.CompactTextString(m) }
func (*TweetEntity) ProtoMessage()    {}
func (*TweetEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{22}
}

func (m *TweetEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TweetEntity.Unmarshal(m, b)
}
func (m *TweetEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TweetEntity.Marshal(b, m, deterministic)
}
func (m *TweetEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TweetEntity.Merge(m, src)
}
func (m *TweetEntity) XXX_Size() int {
	return xxx_messageInfo_TweetEntity.Size(m)
}
func (m *TweetEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_TweetEntity.DiscardUnknown(m)
}

var xxx_messageInfo_TweetEntity proto.InternalMessageInfo

func (m *TweetEntity) GetTweetId() uint64 {
	if m != nil {
		return m.TweetId
	}
	return 0
}

func (m *TweetEntity) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *TweetEntity) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *TweetEntity) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "pb.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "pb.HelloReply")
	proto.RegisterType((*StopFollowingRequest)(nil), "pb.StopFollowingRequest")
	proto.RegisterType((*StopFollowingResponse)(nil), "pb.StopFollowingResponse")
	proto.RegisterType((*StartFollowingRequest)(nil), "pb.StartFollowingRequest")
	proto.RegisterType((*StartFollowingResponse)(nil), "pb.StartFollowingResponse")
	proto.RegisterType((*UserCheckWhetherFollowingRequest)(nil), "pb.UserCheckWhetherFollowingRequest")
	proto.RegisterType((*UserCheckWhetherFollowingResponse)(nil), "pb.UserCheckWhetherFollowingResponse")
	proto.RegisterType((*FindAllUsersRequest)(nil), "pb.FindAllUsersRequest")
	proto.RegisterType((*FindAllUsersResponse)(nil), "pb.FindAllUsersResponse")
	proto.RegisterType((*UserAddTweetRequest)(nil), "pb.UserAddTweetRequest")
	proto.RegisterType((*UserAddTweetResponse)(nil), "pb.UserAddTweetResponse")
	proto.RegisterType((*UserSelectByIdResponse)(nil), "pb.UserSelectByIdResponse")
	proto.RegisterType((*UserEntity)(nil), "pb.UserEntity")
	proto.RegisterType((*UserSelectByNameRequest)(nil), "pb.UserSelectByNameRequest")
	proto.RegisterType((*UserSelectByNameResponse)(nil), "pb.UserSelectByNameResponse")
	proto.RegisterType((*NewUserRequest)(nil), "pb.NewUserRequest")
	proto.RegisterType((*NewUserResponse)(nil), "pb.NewUserResponse")
	proto.RegisterType((*NewTweetRequest)(nil), "pb.NewTweetRequest")
	proto.RegisterType((*NewTweetResponse)(nil), "pb.NewTweetResponse")
	proto.RegisterType((*SelectByIdRequest)(nil), "pb.SelectByIdRequest")
	proto.RegisterType((*TweetSelectByIdResponse)(nil), "pb.TweetSelectByIdResponse")
	proto.RegisterType((*TweetEntity)(nil), "pb.TweetEntity")
}

func init() {
	proto.RegisterFile("backend.proto", fileDescriptor_5ab9ba5b8d8b2ba5)
}

var fileDescriptor_5ab9ba5b8d8b2ba5 = []byte{
	// 764 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x4e, 0xdb, 0x4a,
	0x10, 0xce, 0x1f, 0xf9, 0x19, 0x82, 0xe1, 0x2c, 0x3f, 0x71, 0x0c, 0x3a, 0x0a, 0x7b, 0x38, 0x9c,
	0xe8, 0x48, 0xe4, 0x02, 0x7a, 0x89, 0x2a, 0x01, 0x85, 0x92, 0x1b, 0x5a, 0x05, 0xaa, 0x5e, 0x46,
	0x8e, 0xbd, 0x04, 0x37, 0x8e, 0xed, 0x7a, 0x37, 0x8a, 0x72, 0xd3, 0xa7, 0xea, 0xcb, 0xf4, 0x6d,
	0xaa, 0xdd, 0xb5, 0x1d, 0xdb, 0xb1, 0x53, 0x55, 0x15, 0x77, 0xde, 0x99, 0x6f, 0x67, 0xbe, 0x6f,
	0x76, 0x3c, 0xbb, 0xb0, 0x35, 0xd2, 0x8d, 0x09, 0x71, 0xcc, 0x9e, 0xe7, 0xbb, 0xcc, 0x45, 0x25,
	0x6f, 0x84, 0x31, 0x34, 0xef, 0x89, 0x6d, 0xbb, 0x03, 0xf2, 0x75, 0x46, 0x28, 0x43, 0x08, 0x2a,
	0x8e, 0x3e, 0x25, 0x6a, 0xb1, 0x53, 0xec, 0x36, 0x06, 0xe2, 0x1b, 0x9f, 0x02, 0x04, 0x18, 0xcf,
	0x5e, 0x20, 0x15, 0x6a, 0x53, 0x42, 0xa9, 0x3e, 0x0e, 0x41, 0xe1, 0x12, 0x8f, 0x60, 0xef, 0x91,
	0xb9, 0xde, 0x9d, 0x6b, 0xdb, 0xee, 0xdc, 0x72, 0xc6, 0x61, 0xcc, 0x13, 0x50, 0xa8, 0x3b, 0xf3,
	0x0d, 0x32, 0x9c, 0x51, 0xe2, 0x0f, 0x2d, 0x53, 0x6c, 0xac, 0x0c, 0x9a, 0xd2, 0xfa, 0x89, 0x12,
	0xbf, 0x6f, 0x72, 0x14, 0xd3, 0xfd, 0x31, 0x61, 0x11, 0xaa, 0x24, 0x51, 0xd2, 0x2a, 0x51, 0xf8,
	0x3f, 0xd8, 0x4f, 0xe5, 0xa0, 0x9e, 0xeb, 0x50, 0x82, 0x14, 0x28, 0xb9, 0x13, 0x11, 0xb8, 0x3e,
	0x28, 0xb9, 0x13, 0x6c, 0x70, 0xa0, 0xee, 0xb3, 0x57, 0x65, 0xd3, 0x85, 0x83, 0x74, 0x92, 0x1c,
	0x3a, 0x0e, 0x74, 0xf8, 0x9e, 0x9b, 0x17, 0x62, 0x4c, 0x3e, 0xbf, 0x10, 0xf6, 0x42, 0xfc, 0x57,
	0x65, 0x76, 0x01, 0xc7, 0x6b, 0xf2, 0xe5, 0x90, 0xdc, 0x87, 0xdd, 0x3b, 0xcb, 0x31, 0xaf, 0x6c,
	0x9b, 0xef, 0xa5, 0x01, 0x2f, 0x7c, 0x09, 0x7b, 0x49, 0x73, 0xb0, 0xfd, 0x04, 0x36, 0x38, 0x05,
	0xaa, 0x16, 0x3b, 0xe5, 0xee, 0xe6, 0xb9, 0xd2, 0xf3, 0x46, 0x3d, 0x8e, 0xb8, 0x75, 0x98, 0xc5,
	0x16, 0x03, 0xe9, 0xc4, 0xf7, 0xb0, 0xcb, 0x8d, 0x57, 0xa6, 0xf9, 0x34, 0x27, 0x84, 0x85, 0x62,
	0x5b, 0x50, 0x4b, 0xaa, 0xac, 0xce, 0xa4, 0x3e, 0x15, 0x6a, 0x86, 0xeb, 0x30, 0xe2, 0x30, 0x21,
	0xac, 0x31, 0x08, 0x97, 0xf8, 0x14, 0xf6, 0x92, 0x91, 0x72, 0x64, 0x5c, 0xc2, 0x01, 0xc7, 0x3d,
	0x12, 0x9b, 0x18, 0xec, 0x7a, 0xd1, 0x37, 0x23, 0x24, 0x86, 0x0a, 0xcf, 0x22, 0xb0, 0xab, 0x84,
	0x85, 0x0f, 0x7f, 0x2f, 0x02, 0x2c, 0x8d, 0xf9, 0x3c, 0x0f, 0xa1, 0x21, 0x1c, 0xe2, 0x77, 0x91,
	0x4c, 0xeb, 0xdc, 0xf0, 0xa0, 0x4f, 0x09, 0xd2, 0xa0, 0xee, 0xe9, 0x94, 0xce, 0x5d, 0xdf, 0x54,
	0xcb, 0xd2, 0x17, 0xae, 0xd1, 0x11, 0x34, 0x9e, 0xc5, 0x51, 0xf0, 0xd2, 0x55, 0x3a, 0xe5, 0x6e,
	0x65, 0xb0, 0x34, 0xa0, 0xbf, 0x01, 0x9e, 0xc3, 0x83, 0xa2, 0xea, 0x86, 0x70, 0xc7, 0x2c, 0xe8,
	0x00, 0xaa, 0x8c, 0xab, 0xa7, 0x6a, 0x55, 0xf8, 0x82, 0x15, 0x3e, 0x83, 0x56, 0x5c, 0x34, 0x67,
	0xb1, 0xee, 0x9f, 0x7e, 0x0b, 0xea, 0x2a, 0xfc, 0x37, 0xaa, 0x74, 0x0f, 0xca, 0x03, 0x99, 0x73,
	0x73, 0x98, 0x25, 0x51, 0x8f, 0x62, 0xaa, 0x1e, 0x6d, 0x10, 0xdf, 0x43, 0x6f, 0x6e, 0x86, 0xa7,
	0xca, 0xd7, 0x1f, 0xe7, 0x26, 0xfe, 0x1f, 0xb6, 0xa3, 0x48, 0x01, 0x81, 0xbc, 0x9a, 0xe3, 0x77,
	0x02, 0xfb, 0xa7, 0x7d, 0x74, 0x06, 0x3b, 0xcb, 0x28, 0x41, 0xca, 0x36, 0xd4, 0x45, 0x21, 0x97,
	0x71, 0x6a, 0x62, 0xdd, 0x37, 0xf1, 0x3f, 0xf0, 0x57, 0xbc, 0x95, 0x64, 0x5a, 0x05, 0x4a, 0x11,
	0xb2, 0x64, 0x99, 0xf8, 0x12, 0x5a, 0x22, 0x60, 0x46, 0xd3, 0x1d, 0x43, 0x79, 0x4a, 0xc7, 0x41,
	0x35, 0xb7, 0x79, 0x35, 0x05, 0x32, 0x28, 0x27, 0xf7, 0xe1, 0x6f, 0xb0, 0x19, 0xb3, 0xad, 0x21,
	0x13, 0x97, 0x5b, 0xca, 0x93, 0x5b, 0x4e, 0xc8, 0x45, 0xc7, 0xd0, 0x34, 0x7c, 0xa2, 0x33, 0x62,
	0x0e, 0x99, 0x35, 0x25, 0x6a, 0x45, 0xb8, 0x37, 0x03, 0xdb, 0x93, 0x35, 0x25, 0xe7, 0x3f, 0x36,
	0xa0, 0x76, 0x2d, 0xef, 0x06, 0xf4, 0x1e, 0xb6, 0x53, 0x4a, 0xd0, 0x3e, 0x27, 0xbd, 0x52, 0x03,
	0xed, 0x30, 0xd2, 0xb2, 0xaa, 0x1a, 0x17, 0xd0, 0x1b, 0xa8, 0x05, 0x07, 0x8b, 0x10, 0x47, 0x26,
	0xfb, 0x45, 0xdb, 0x4d, 0xd8, 0xa2, 0x5d, 0x1f, 0x60, 0x27, 0xdd, 0x98, 0xe8, 0x30, 0x6c, 0xc1,
	0x8c, 0xee, 0xd6, 0x8e, 0xb2, 0x9d, 0x51, 0xc0, 0x5b, 0x50, 0x92, 0xd3, 0x20, 0x4f, 0x8e, 0x96,
	0x0e, 0x94, 0x50, 0x73, 0x03, 0xcd, 0xf8, 0xf0, 0x41, 0xad, 0x10, 0x9d, 0x1a, 0x6c, 0x9a, 0xba,
	0xea, 0x88, 0x07, 0x89, 0x4f, 0x52, 0x19, 0x24, 0x63, 0xe4, 0xca, 0x20, 0x59, 0x43, 0x17, 0x17,
	0xd0, 0x17, 0x68, 0xe7, 0x8e, 0x76, 0x74, 0x12, 0x66, 0x5f, 0x77, 0xd3, 0x68, 0xff, 0xfe, 0x02,
	0x15, 0xe5, 0xea, 0x83, 0x92, 0xbc, 0xe0, 0x50, 0x5b, 0x14, 0x2f, 0xeb, 0x66, 0x95, 0x05, 0xcc,
	0xbe, 0x0f, 0x71, 0x01, 0xdd, 0xc1, 0x56, 0xe2, 0xe6, 0x46, 0xaa, 0x84, 0xaf, 0x3e, 0x18, 0xb4,
	0x76, 0x86, 0x27, 0x8a, 0xd3, 0x83, 0xfa, 0xa3, 0xbe, 0x10, 0x0f, 0x12, 0xb4, 0xc3, 0x81, 0xf1,
	0xf7, 0x8b, 0xa6, 0xc4, 0x2c, 0x9e, 0xbd, 0xc0, 0x85, 0x51, 0x55, 0x3c, 0x76, 0x2e, 0x7e, 0x06,
	0x00, 0x00, 0xff, 0xff, 0xb7, 0x5d, 0xfa, 0xbc, 0xfd, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BackendClient is the client API for Backend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BackendClient interface {
	TweetSelectById(ctx context.Context, in *SelectByIdRequest, opts ...grpc.CallOption) (*TweetSelectByIdResponse, error)
	NewUser(ctx context.Context, in *NewUserRequest, opts ...grpc.CallOption) (*NewUserResponse, error)
	UserSelectByName(ctx context.Context, in *UserSelectByNameRequest, opts ...grpc.CallOption) (*UserSelectByNameResponse, error)
	UserSelectById(ctx context.Context, in *SelectByIdRequest, opts ...grpc.CallOption) (*UserSelectByIdResponse, error)
	UserAddTweet(ctx context.Context, in *UserAddTweetRequest, opts ...grpc.CallOption) (*UserAddTweetResponse, error)
	FindAllUsers(ctx context.Context, in *FindAllUsersRequest, opts ...grpc.CallOption) (*FindAllUsersResponse, error)
	UserCheckWhetherFollowing(ctx context.Context, in *UserCheckWhetherFollowingRequest, opts ...grpc.CallOption) (*UserCheckWhetherFollowingResponse, error)
	StartFollowing(ctx context.Context, in *StartFollowingRequest, opts ...grpc.CallOption) (*StartFollowingResponse, error)
	StopFollowing(ctx context.Context, in *StopFollowingRequest, opts ...grpc.CallOption) (*StopFollowingResponse, error)
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type backendClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendClient(cc grpc.ClientConnInterface) BackendClient {
	return &backendClient{cc}
}

func (c *backendClient) TweetSelectById(ctx context.Context, in *SelectByIdRequest, opts ...grpc.CallOption) (*TweetSelectByIdResponse, error) {
	out := new(TweetSelectByIdResponse)
	err := c.cc.Invoke(ctx, "/pb.Backend/TweetSelectById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) NewUser(ctx context.Context, in *NewUserRequest, opts ...grpc.CallOption) (*NewUserResponse, error) {
	out := new(NewUserResponse)
	err := c.cc.Invoke(ctx, "/pb.Backend/NewUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) UserSelectByName(ctx context.Context, in *UserSelectByNameRequest, opts ...grpc.CallOption) (*UserSelectByNameResponse, error) {
	out := new(UserSelectByNameResponse)
	err := c.cc.Invoke(ctx, "/pb.Backend/UserSelectByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) UserSelectById(ctx context.Context, in *SelectByIdRequest, opts ...grpc.CallOption) (*UserSelectByIdResponse, error) {
	out := new(UserSelectByIdResponse)
	err := c.cc.Invoke(ctx, "/pb.Backend/UserSelectById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) UserAddTweet(ctx context.Context, in *UserAddTweetRequest, opts ...grpc.CallOption) (*UserAddTweetResponse, error) {
	out := new(UserAddTweetResponse)
	err := c.cc.Invoke(ctx, "/pb.Backend/UserAddTweet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) FindAllUsers(ctx context.Context, in *FindAllUsersRequest, opts ...grpc.CallOption) (*FindAllUsersResponse, error) {
	out := new(FindAllUsersResponse)
	err := c.cc.Invoke(ctx, "/pb.Backend/FindAllUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) UserCheckWhetherFollowing(ctx context.Context, in *UserCheckWhetherFollowingRequest, opts ...grpc.CallOption) (*UserCheckWhetherFollowingResponse, error) {
	out := new(UserCheckWhetherFollowingResponse)
	err := c.cc.Invoke(ctx, "/pb.Backend/UserCheckWhetherFollowing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) StartFollowing(ctx context.Context, in *StartFollowingRequest, opts ...grpc.CallOption) (*StartFollowingResponse, error) {
	out := new(StartFollowingResponse)
	err := c.cc.Invoke(ctx, "/pb.Backend/StartFollowing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) StopFollowing(ctx context.Context, in *StopFollowingRequest, opts ...grpc.CallOption) (*StopFollowingResponse, error) {
	out := new(StopFollowingResponse)
	err := c.cc.Invoke(ctx, "/pb.Backend/StopFollowing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/pb.Backend/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendServer is the server API for Backend service.
type BackendServer interface {
	TweetSelectById(context.Context, *SelectByIdRequest) (*TweetSelectByIdResponse, error)
	NewUser(context.Context, *NewUserRequest) (*NewUserResponse, error)
	UserSelectByName(context.Context, *UserSelectByNameRequest) (*UserSelectByNameResponse, error)
	UserSelectById(context.Context, *SelectByIdRequest) (*UserSelectByIdResponse, error)
	UserAddTweet(context.Context, *UserAddTweetRequest) (*UserAddTweetResponse, error)
	FindAllUsers(context.Context, *FindAllUsersRequest) (*FindAllUsersResponse, error)
	UserCheckWhetherFollowing(context.Context, *UserCheckWhetherFollowingRequest) (*UserCheckWhetherFollowingResponse, error)
	StartFollowing(context.Context, *StartFollowingRequest) (*StartFollowingResponse, error)
	StopFollowing(context.Context, *StopFollowingRequest) (*StopFollowingResponse, error)
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

// UnimplementedBackendServer can be embedded to have forward compatible implementations.
type UnimplementedBackendServer struct {
}

func (*UnimplementedBackendServer) TweetSelectById(ctx context.Context, req *SelectByIdRequest) (*TweetSelectByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TweetSelectById not implemented")
}
func (*UnimplementedBackendServer) NewUser(ctx context.Context, req *NewUserRequest) (*NewUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewUser not implemented")
}
func (*UnimplementedBackendServer) UserSelectByName(ctx context.Context, req *UserSelectByNameRequest) (*UserSelectByNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserSelectByName not implemented")
}
func (*UnimplementedBackendServer) UserSelectById(ctx context.Context, req *SelectByIdRequest) (*UserSelectByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserSelectById not implemented")
}
func (*UnimplementedBackendServer) UserAddTweet(ctx context.Context, req *UserAddTweetRequest) (*UserAddTweetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserAddTweet not implemented")
}
func (*UnimplementedBackendServer) FindAllUsers(ctx context.Context, req *FindAllUsersRequest) (*FindAllUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllUsers not implemented")
}
func (*UnimplementedBackendServer) UserCheckWhetherFollowing(ctx context.Context, req *UserCheckWhetherFollowingRequest) (*UserCheckWhetherFollowingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCheckWhetherFollowing not implemented")
}
func (*UnimplementedBackendServer) StartFollowing(ctx context.Context, req *StartFollowingRequest) (*StartFollowingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartFollowing not implemented")
}
func (*UnimplementedBackendServer) StopFollowing(ctx context.Context, req *StopFollowingRequest) (*StopFollowingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopFollowing not implemented")
}
func (*UnimplementedBackendServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterBackendServer(s *grpc.Server, srv BackendServer) {
	s.RegisterService(&_Backend_serviceDesc, srv)
}

func _Backend_TweetSelectById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).TweetSelectById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Backend/TweetSelectById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).TweetSelectById(ctx, req.(*SelectByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_NewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).NewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Backend/NewUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).NewUser(ctx, req.(*NewUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_UserSelectByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSelectByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).UserSelectByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Backend/UserSelectByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).UserSelectByName(ctx, req.(*UserSelectByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_UserSelectById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).UserSelectById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Backend/UserSelectById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).UserSelectById(ctx, req.(*SelectByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_UserAddTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAddTweetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).UserAddTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Backend/UserAddTweet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).UserAddTweet(ctx, req.(*UserAddTweetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_FindAllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).FindAllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Backend/FindAllUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).FindAllUsers(ctx, req.(*FindAllUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_UserCheckWhetherFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCheckWhetherFollowingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).UserCheckWhetherFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Backend/UserCheckWhetherFollowing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).UserCheckWhetherFollowing(ctx, req.(*UserCheckWhetherFollowingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_StartFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartFollowingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).StartFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Backend/StartFollowing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).StartFollowing(ctx, req.(*StartFollowingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_StopFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopFollowingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).StopFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Backend/StopFollowing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).StopFollowing(ctx, req.(*StopFollowingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Backend_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Backend/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Backend_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Backend",
	HandlerType: (*BackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TweetSelectById",
			Handler:    _Backend_TweetSelectById_Handler,
		},
		{
			MethodName: "NewUser",
			Handler:    _Backend_NewUser_Handler,
		},
		{
			MethodName: "UserSelectByName",
			Handler:    _Backend_UserSelectByName_Handler,
		},
		{
			MethodName: "UserSelectById",
			Handler:    _Backend_UserSelectById_Handler,
		},
		{
			MethodName: "UserAddTweet",
			Handler:    _Backend_UserAddTweet_Handler,
		},
		{
			MethodName: "FindAllUsers",
			Handler:    _Backend_FindAllUsers_Handler,
		},
		{
			MethodName: "UserCheckWhetherFollowing",
			Handler:    _Backend_UserCheckWhetherFollowing_Handler,
		},
		{
			MethodName: "StartFollowing",
			Handler:    _Backend_StartFollowing_Handler,
		},
		{
			MethodName: "StopFollowing",
			Handler:    _Backend_StopFollowing_Handler,
		},
		{
			MethodName: "SayHello",
			Handler:    _Backend_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend.proto",
}
