package store


const METHOD_SessionInit = "METHOD_SessionInit"
const METHOD_SessionRead = "METHOD_SessionRead"
const METHOD_SessionDestroy = "METHOD_SessionDestroy"
const METHOD_SessionGC = "METHOD_SessionGC"
const METHOD_SessionGet = "METHOD_SessionGet"
const METHOD_SessionSet = "METHOD_SessionSet"
const METHOD_SessionDelete = "METHOD_SessionDelete"
const METHOD_SessionID = "METHOD_SessionID"
const METHOD_UserCreate = "METHOD_UserCreate"
const METHOD_UserDelete = "METHOD_UserDelete"
const METHOD_UserGet = "METHOD_UserGet"
const METHOD_UserUpdate = "METHOD_UserUpdate"
const METHOD_UserFindAll = "METHOD_UserFindAll"
const METHOD_UserAddTweetToUserDB = "METHOD_UserAddTweetToUserDB"
const METHOD_UserCheckWhetherFollowingGetDB = "METHOD_UserCheckWhetherFollowingGetDB"
const METHOD_UserStartFollowingDB = "METHOD_UserStartFollowingDB"
const METHOD_UserStopFollowingDB = "METHOD_UserStopFollowingDB"
const METHOD_TweetCreate = "METHOD_TweetCreate"
const METHOD_TweetGet = "METHOD_TweetGet"
const METHOD_TweetDelete = "METHOD_TweetDelete"
const METHOD_TweetDeleteByCreatedTime = "METHOD_TweetDeleteByCreatedTime"
const METHOD_TweetGetAll = "METHOD_TweetGetAll"
